Projets JSF/ProjetJSF_ECommerce/src/controller/CartController.java
package controller;

import modele.Client;
import modele.Item;
import service.ServiceCart;
import service.ServiceItem;
import util.Achat;
import util.CardExpiredException;
import util.InfoCB;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.ValueChangeEvent;
import javax.persistence.criteria.CriteriaBuilder;
import java.io.Serializable;
import java.util.*;

@ManagedBean(name = "cartCtrl")
@SessionScoped
public class CartController implements Serializable {
    private Client client;
    private List<Achat> panier = null;
    private InfoCB infoCB;
    private Boolean authentifie;
    private String numeroCB;
    private Date expirationDate;

    public Client getClient() {
        return client;
    }
    public void setClient(Client client) {
        this.client = client;
    }
    public List<Achat> getPanier() {
        return panier;
    }
    public void setPanier(List<Achat> panier) {
        this.panier = panier;
    }
    public InfoCB getInfoCB() {
        return infoCB;
    }
    public void setInfoCB(InfoCB infoCB) {
        this.infoCB = infoCB;
    }
    public Boolean getAuthentifie() {
        return authentifie;
    }
    public void setAuthentifie(Boolean authentifie) {
        this.authentifie = authentifie;
    }
    public String getNumeroCB() {
        return numeroCB;
    }

    public void setNumeroCB(String numeroCB) {
        this.numeroCB = numeroCB;
    }

    public Date getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    //Login
    private String nom;
    private String prenom;

    public String getNom() {
        return nom;
    }
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return prenom;
    }
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String doLogin() {
        this.client = ServiceCart.getSingleton().findOrCreate(this.nom, this.prenom);
        this.authentifie = true;
        this.panier = new ArrayList<>();
        this.infoCB = new InfoCB();
        return "showItems";
    }

    public String doHome() {
        this.client = null;
        this.authentifie = false;

        return "index";
    }

    //---------------------- ShowItems
    public List<Item> getEnsItems() {
        return ServiceItem.getSingleton().findAllItem();
    }

    private Item itemSelectionne;

    public String doSelectItem(Item item) {
        this.itemSelectionne = item;
        this.panier.add(new Achat(item.getId(), 1, item.getPrix(), item.getTitre()));
        return "showPanier";
    }

    //--------------------- ShowPanier
    private Integer nouvQte;
    private Achat achatSelectionne;


    public Double getTotalPanier() {
        return ServiceCart.getSingleton().valeurDuPanier(panier);
    }

    public void updateQte(ValueChangeEvent event) {
        nouvQte = (Integer) event.getNewValue();
    }

    public String doModifierAchat(Achat achat) {
        this.achatSelectionne = achat;
        achatSelectionne.setQuantite(nouvQte);
        this.panier.remove(achat);
        this.panier.add(achatSelectionne);
        return "showPanier";
    }

    public String doSupprimerAchat(Achat a) {
        this.achatSelectionne = a;
        this.panier.remove(a);

        if (this.panier.isEmpty()) return "showItems";
        return "showPanier";
    }

    public String doListItem(){
        return "showItems";
    }

    //----------------------- Validation
    public String doValidation(){
        this.infoCB = new InfoCB(numeroCB,expirationDate);
        try {
            ServiceCart.getSingleton().validerPanier(client,panier,infoCB);
        } catch (CardExpiredException e) {
            e.printStackTrace();
        }
        return "logout";
    }
}

Projets JSF/ProjetJSF_ECommerce/src/controller/ItemController.java
package controller;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.Date;

@ManagedBean(name = "itemCtrl")
@ViewScoped
public class ItemController implements Serializable {
    private String numeroCB;
    private Date expirationDate;
}

Projets JSF/ProjetJSF_ECommerce/web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
   <title>Index</title>
</h:head>
<h:body>
   <f:view>
      <h3>Frais Kilometrique : Inscription</h3>
      <h:form>
         <h:panelGrid columns="2">
            <h:outputLabel value="Nom:"/>
            <h:inputText value="#{cartCtrl.nom}" required="true" requiredMessage="Le nom est obligatoire"/>

            <h:outputLabel value="Prenom:"/>
            <h:inputText value="#{cartCtrl.prenom}"/>

            <h:commandButton value="Login" action="#{cartCtrl.doLogin}"/>
         </h:panelGrid>
      </h:form>
   </f:view>
</h:body>
</html>

Projets JSF/ProjetJSF_ECommerce/web/logout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view>
    <h3>E-Cultura : Déconnexion</h3>
    <h:outputText value="Merci de votre commande Monsieur #{cartCtrl.nom}"/>
</f:view>
</html>

Projets JSF/ProjetJSF_ECommerce/web/paiement.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Paiement</title>
</h:head>
<h:body>
    <f:view>
        <h3>E-Cultura : Paiement</h3>
        <h:form>
            <h:panelGrid columns="3">
                <h:outputLabel value="Numero CB :" />
                <h:inputText id="numeroCBId" value="#{cartCtrl.numeroCB}" required="true" immediate="true">
                    <f:validateRegex pattern="[0-9]{6,12}" />
                </h:inputText>
                <h:message for="numeroCBId" errorClass="error" />

                <h:outputLabel value="Date d'expiration de la CB" />
                <h:inputText id="dateExpBId" value="#{cartCtrl.expirationDate}" required="true" immediate="true">
                    <f:convertDateTime pattern="dd//MM/yyyy" />
                </h:inputText>
                <h:message for="dateExpBId" errorClass="error" />

                <h:commandButton action="#{cartCtrl.doValidation}" value="Valider Paiement CB"/>

            </h:panelGrid>
        </h:form>

    </f:view>
</h:body>
</html>

Projets JSF/ProjetJSF_ECommerce/web/showItems.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Index</title>
</h:head>
<h:body>
    <f:view>
        <h3>E-Cultura : Produits</h3>
        <h:form>
            <h:dataTable cellspacing="6" columns="2" value="#{cartCtrl.ensItems}" var="i">
                <h:column>
                    <f:facet name = "header">Titre</f:facet>
                    <h:outputText value="#{i.titre}" required="true" requiredMessage="Le nom est obligatoire"/>
                </h:column>

                <h:column>
                    <f:facet name = "header">Catégorie</f:facet>
                    <h:outputText value="#{i.categorie}" required="true" requiredMessage="obligatoire"/>
                </h:column>

                <h:column>
                    <f:facet name = "header">Prix</f:facet>
                    <h:outputText value="#{i.prix}" required="true" requiredMessage="obligatoire"/>
                </h:column>

                <h:column>
                    <f:facet name = "header">Panier</f:facet>
                    <h:commandButton value="Ajouter" action="#{cartCtrl.doSelectItem(i)}"/>
                </h:column>
            </h:dataTable>
        </h:form>

    </f:view>
</h:body>
</html>

Projets JSF/ProjetJSF_ECommerce/web/showPanier.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Panier</title>
</h:head>
<h:body>
    <f:view>
        <h3>E-Cultura : Panier</h3>
        <h:form>
            <h:dataTable cellspacing="6" columns="2" value="#{cartCtrl.panier}" var="achat">
                <h:column>
                    <f:facet name = "header">Titre</f:facet>
                    <h:outputText value="#{achat.titre}" required="true"/>
                </h:column>

                <h:column>
                    <f:facet name = "header">Quantité</f:facet>
                    <h:inputText value="#{achat.quantite}" valueChangeListener="#{cartCtrl.updateQte}">
                        <f:validateLongRange minimum="1" maximum="3"/>
                    </h:inputText>
                </h:column>

                <h:column>
                    <f:facet name = "header">Prix</f:facet>
                    <h:outputText value="#{achat.prix}" required="true">
                        <f:convertNumber type="currency" pattern="####.##"/>
                    </h:outputText>

                    <f:facet name="footer">
                        <h:outputText value="#{cartCtrl.totalPanier}" styleClass="prix">
                            <f:convertNumber type="currency" pattern="####.##"/>
                        </h:outputText>
                    </f:facet>
                </h:column>

                <h:column>
                    <h:commandButton value="modifier" action="#{cartCtrl.doModifierAchat(achat)}"/>
                </h:column>
                <h:column>
                    <h:commandButton value="supprimer" action="#{cartCtrl.doSupprimerAchat(achat)}"/>
                </h:column>

            </h:dataTable>
        </h:form>
        <h:form>
            <h:panelGrid columns="2" cellspacing="10">
                <h:commandButton value="Valider le panier" action="paiement"/>
                <h:commandButton value="Catalogue" action="#{cartCtrl.doListItem}"/>
            </h:panelGrid>
        </h:form>
    </f:view>
</h:body>
</html>